### PR TITLE
test

### PR DESCRIPTION
**Pull request by kyle-house-sp**
http://media.giphy.com/media/3o85xvYjl3CwW7BbnW/giphy.gif

### CODE REVIEW

**Comment by kyle-house-sp** [comment]
http://media.giphy.com/media/3o85xvYjl3CwW7BbnW/giphy.gif

**Comment by jeffbyrnes** [comment]
@kyle-house-sp glad you’re getting some use out of this gem. Get the impression you meant to PR that to your own fork? Interesting, if opinionated, changes… reporting this in to DataDog is a cool idea.

**Comment by kyle-house-sp** [comment]
shame...sorry about that, thought it was my fork. I was testing +1's via gifs.

The metrics to datadog has been really nice for us to detect when other nodes see different results. Be happy to externalize it to make it optional, was just a quick fix to fit my needs. Anyway, sorry about that.

screen shot 2015-11-04 at 3 56 26 pm

**Comment by jeffbyrnes** [comment]
@kyle-house-sp no problem! Would love you to rework it to be optional, and have it be a feature for this gem; I’ve been considering using DataDog for us for other things.

Thanks for sharing the screenshots.

**Pull request closed without merging**
